### ISSUE TITLE
Anotha One

### ISSUE THREAD

**Issue by yunginnanet** [liamg/grace#4]
The rate at which you release projects along with quality and effectiveness of said projects is beginning to cause many of the rest of us to **_look bad_**. Every day I wake up and am invaded with intrusive thoughts to the tune of:

> "when will you catch up to liamg?"

> "he's not just making IRC bots anymore, why are you still committing to your silly little girc fork?"

> "maybe if you were good at anything you would spend as much time as liamg does with the syscall and unsafe libraries but here you are still learning how to use sync.Pool properly"

I presume one should be able to reproduce this bug on many platforms. I beg of you on behalf of the entire golang community to **_slow down_** and maybe just release a dud or two so we don't all look as bad.

Thanks One Million!

---

P.S: I don't know what `Discussions` is but this is an issue.

**Comment by liamg** [comment]
Hi @yunginnanet - I'm sick at the moment and this cheered me up massively, so thank you! :laughing: 

I'm very flattered, but I can assure you I have similar intrusive thoughts:

> What if people read your code and realise you don't really know what you're doing?

> Has anyone noticed that you haven't packaged your projects for Ubuntu etc. because you don't actually know how?

> You still don't have a decent knowledge of kubernetes seemingly unlike everyone else in the known universe?

Also the anxiety that builds up from releasing too many hastily hacked together projects and not spending the proper amount of time on maintaining them is approaching dangerous levels :laughing: 

Anyway, thank you, you've made my day! :smiley:

**Comment by yunginnanet** [comment]
## Resolution:

everyone has imposter syndrome
